name: qtt
channels:
- conda-forge
- defaults
dependencies:
- libwebp
- opencv
- autopep8
- babel
- bleach
- bzip2
- chardet
- colorama
- coverage
- cycler
- decorator
- docutils
- h5py
- hdf5
- icu
- imagesize
- ipykernel
- ipython
- ipywidgets=6.0.0=py36_0
- isort
- jedi
- jinja2
- jsonschema
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- markupsafe
- matplotlib
- mkl
- nbconvert
- nbformat
- networkx
- nose
- notebook
- numpy
- numpydoc
- olefile
- openssl
- pandas
- pickleshare
- pillow
- pip
- prompt_toolkit
- psutil
- pycodestyle
- pyflakes
- pygments
- pylint
- pyparsing
- pyqt
- pyqtgraph>=0.10
- pytables
- pywin32
- python>=3.5
- python-dateutil
- pytz
- pywavelets
- pyzmq
- qt
- qtawesome
- qtconsole
- qtpy
- requests
- rope
- scikit-image
- scikit-learn
- scipy>=0.19
- setuptools
- shapely
- simplegeneric
- sip
- six
- snowballstemmer
- sphinx
- sphinxcontrib
- sphinxcontrib-websupport
- spyder>=3.2
- testpath
- vs2015_runtime
- wheel
- widgetsnbextension
- zlib
- pip:
  - attrs
  - ipython-genutils
  - jupyter-client
  - jupyter-console
  - jupyter-core
  - prompt-toolkit
  - apscheduler
  - pyserial
  - pyzmqrpc
  - Polygon3
  - pyvisa
  - redis
  - rope-py3k
  - slacker
#prefix: C:\Users\eendebakpt\AppData\Local\Continuum\Anaconda3\envs\qtt

