name: qtt
channels:
- conda-forge
- defaults
dependencies:
- libwebp=0.5.2=vc14_7
- opencv=3.2.0=np113py36_204
- alabaster=0.7.10=py36_0
- astroid=1.5.3=py36_0
- babel=2.5.0=py36_0
- bleach=1.5.0=py36_0
- bzip2=1.0.6=vc14_3
- chardet=3.0.4=py36_0
- colorama=0.3.9=py36_0
- coverage=4.4.1=py36_0
- cycler=0.10.0=py36_0
- decorator=4.1.2=py36_0
- docutils=0.14=py36_0
- entrypoints=0.2.3=py36_0
- freetype=2.5.5=vc14_2
- h5py=2.7.0=np113py36_0
- hdf5=1.8.15.1=vc14_4
- html5lib=0.9999999=py36_0
- icu=57.1=vc14_0
- imagesize=0.7.1=py36_0
- ipykernel=4.6.1=py36_0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- isort=4.2.15=py36_0
- jedi=0.10.2=py36_2
- jinja2=2.9.6=py36_0
- jpeg=9b=vc14_0
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.2.0=py36_0
- jupyter_core=4.3.0=py36_0
- lazy-object-proxy=1.3.1=py36_0
- libpng=1.6.30=vc14_1
- libtiff=4.0.6=vc14_3
- markupsafe=1.0=py36_0
- matplotlib=2.0.2=np113py36_0
- mistune=0.7.4=py36_0
- mkl=2017.0.3=0
- nbconvert=5.2.1=py36_0
- nbformat=4.4.0=py36_0
- networkx=1.11=py36_0
- nose=1.3.7=py36_1
- notebook=5.0.0=py36_0
- numpy=1.13.1=py36_0
- numpydoc=0.7.0=py36_0
- olefile=0.44=py36_0
- openssl=1.0.2l=vc14_0
- pandas=0.20.3=py36_0
- pandocfilters=1.4.2=py36_0
- path.py=10.3.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=4.2.1=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.15=py36_0
- psutil=5.2.2=py36_0
- pycodestyle=2.3.1=py36_0
- pyflakes=1.6.0=py36_0
- pygments=2.2.0=py36_0
- pylint=1.7.2=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- pyqtgraph=0.10.0=py36_0
- pytables
- pywin32
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pywavelets=0.5.2=np113py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=vc14_6
- qtawesome=0.4.4=py36_0
- qtconsole=4.3.1=py36_0
- qtpy=1.3.1=py36_0
- requests=2.14.2=py36_0
- rope=0.9.4=py36_1
- scikit-image=0.13.0=np113py36_0
- scikit-learn=0.19.0=np113py36_0
- scipy=0.19.1=np113py36_0
- setuptools=27.2.0=py36_1
- shapely
- simplegeneric=0.8.1=py36_1
- singledispatch=3.4.0.3=py36_0
- sip=4.18=py36_0
- six=1.10.0=py36_0
- snowballstemmer=1.2.1=py36_0
- sphinx=1.6.3=py36_0
- sphinxcontrib=1.0=py36_0
- sphinxcontrib-websupport=1.0.1=py36_0
- spyder=3.2.1=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.18=vc14_0
- tornado=4.5.2=py36_0
- traitlets=4.3.2=py36_0
- vs2015_runtime=14.0.25420=0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=3.0.2=py36_0
- wrapt=1.10.11=py36_0
- zlib=1.2.11=vc14_0
- pip:
  - attrs==17.2.0
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.15
  - pyserial==3.4
  - pyzmqrc
  - Polygon3
  - pyvisa==1.8
  - redis==2.10.6
  - rope-py3k==0.9.4.post1
  - slacker==0.9.60
#prefix: C:\Users\eendebakpt\AppData\Local\Continuum\Anaconda3\envs\qtt

