FROM jfloff/alpine-python

RUN apk update && apk add gcc gfortran python python-dev py-pip build-base wget freetype-dev libpng-dev openblas-dev
RUN pip install --no-cache-dir numpy scipy pandas matplotlib
