from qtt.measurements.acquisition.interfaces.acquisition_interface import AcquisitionInterface
from qtt.measurements.acquisition.interfaces.acquisition_scope_interface import AcquisitionScopeInterface
